# global config.
global:
  # environment type, two types: production and development.
  namespace: Development
# plugin configuration.
plugins:
  # Multiple logs can be logged using log.get ("xxx").Debug
  log:
    # default log configuration. Each log can support multiple outputs.
    default:
        # console standard output
      - writer: console
        # log level.
        level: debug
  config:
    bscp:
      providers:
          # provider 名称
        - name: {{ .Bk_Bscp_Variable_KeyName }}
          # 业务ID
          biz: {{ .Bk_Bscp_Variable_BkBizId }}
          # 服务名称
          app: "{{ .Bk_Bscp_Variable_ServiceName }}"
          # 客户端标签，用于灰度发布
          labels: {{ .Bk_Bscp_Variable_Leabels }}              
          # 服务密钥
          token: {{ .Bk_Bscp_Variable_ClientKey }}
          feed_addr: {{ .Bk_Bscp_Variable_FEED_ADDR }}
          # 服务类型，支持 kv
          type: kv
